#!/bin/bash
cd /usr/local/sbin
rm accounts
rm base_ports
rm base_ports-wc
rm base_script
rm clear_cache
rm connections
rm create
rm create_random
rm create_trial
rm delete_expired
rm diagnose
rm edit_dropbear
rm edit_openssh
rm edit_openvpn
rm edit_ports
rm edit_squid3
rm edit_stunnel4
rm locked_list
rm menu
rm options
rm reboot_sys
rm reboot_sys_auto
rm restart_service
rm server
rm set_multilogin_autokill
rm set_multilogin_autokill_lib
rm show_ports
rm user_delete
rm user_details
rm user_details_lib
rm user_extend
rm user_list
rm user_lock
rm user_unlock
wget 
