#!/bin/bash
source /usr/local/sbin/base-script
clear

echo -e " ╔═══╦╗───╔═══╦═══╦╗─╔╗" | lolcat -a
echo -e " ║╔══╣║───║╔═╗║╔═╗║║─║║" | lolcat -a
echo -e " ║╚══╣║╔══╣╚══╣╚══╣╚═╝║" | lolcat -a
echo -e " ║╔══╣║║╔╗╠══╗╠══╗║╔═╗║" | lolcat -a
echo -e " ║║──║╚╣╔╗║╚═╝║╚═╝║║─║║" | lolcat -a
echo -e " ╚╝──╚═╩╝╚╩═══╩═══╩╝─╚╝" | lolcat -a
echo -e " ╔═╗╔═╗" | lolcat -a
echo -e " ║║╚╝║║" | lolcat -a
echo -e " ║╔╗╔╗╠══╦═╗╔╗╔╗" | lolcat -a
echo -e " ║║║║║║║═╣╔╗╣║║║" | lolcat -a
echo -e " ║║║║║║║═╣║║║╚╝║" | lolcat -a
echo -e " ╚╝╚╝╚╩══╩╝╚╩══╝" | lolcat -a
echo -e ""
echo -e ""
echo -e "   [1] Mengelola Akun Member "
echo -e ""
echo -e "   [2] Mengelola Server "
echo -e ""
echo -e "   [3] Opsi Lanjutan "
echo -e ""
echo -e "   [4] Keluar"
echo -e ""
read -p "$(echo -e " Tentukan Pilihanmu\e[32m [\e[0m1-5\e[32m]\e[0m: ")" menu
echo -e ""
echo -e ""
clear
echo -e "   Perintah di terima  "  | lolcat -a
sleep 1
clear
case $menu in
		1)
		clear
		accounts
		exit
		;;
		2)
		clear
		server
		exit
		;;
		3)
		clear
		options
		exit
		;;
		4)
		clear
		exit
		;;
	esac